version: '3'

services:
  web:
    build:
      context: web/.
      args:
        BUILD_TYPE: docker
    ports:
      - "3003:80"
    environment:
      - HYDRA_ADMIN_URL=http://host.docker.internal:4445
      - PUBLIC_URL=http://host.docker.internal:4444
      - HYDRA_PROXY_URL=http://host.docker.internal:4445